# Generated by Django 4.2.6 on 2023-10-18 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='title',
            new_name='name',
        ),
    ]
