# Generated by Django 4.2.6 on 2023-10-18 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_title_menu_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='DailyMenu',
        ),
    ]
