# Generated by Django 4.2.6 on 2023-10-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_menu_dailymenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymenu',
            name='type',
            field=models.CharField(choices=[('Entree', 'Entree'), ('Pâtes', 'Pâtes'), ('Plat', 'Plat'), ('Dessert', 'Dessert')], default='Entree', max_length=10),
        ),
    ]
