# Generated by Django 4.2.6 on 2023-10-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dailymenu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymenu',
            name='date',
            field=models.DateField(),
        ),
    ]
