# Generated by Django 4.2.6 on 2023-10-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_dailymenu_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymenu',
            name='price',
            field=models.FloatField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
