# Generated by Django 4.2.6 on 2023-10-23 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_dailymenu_price_alter_event_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailymenu',
            old_name='date',
            new_name='today',
        ),
    ]
