# Generated by Django 4.2.6 on 2023-10-31 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_event_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('show', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Bieres Pression', 'Bieres Pression'), ('Bieres Bouteilles', 'Bieres Bouteilles'), ('jus de fruits et sodas', 'jus de fruits et sodas'), ('eaux minerales & sirops', 'eaux minerales & sirops'), ('alcools', 'alcools'), ('aperities', 'aperities'), ('vins', 'vins'), ('boissons chaudes', 'boissons'), ('liqueers & digesties', 'liqueers & digesties')], default='Bieres Pression', max_length=40)),
                ('price', models.FloatField(default=0, max_length=3)),
                ('grams', models.FloatField(default=0, max_length=3)),
            ],
        ),
        migrations.RenameField(
            model_name='dailymenu',
            old_name='limited',
            new_name='promotion',
        ),
    ]
