# Generated by Django 4.2.6 on 2023-11-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_drink_rename_limited_dailymenu_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='grams',
            field=models.CharField(default='/', max_length=50),
        ),
        migrations.AlterField(
            model_name='drink',
            name='price',
            field=models.CharField(default='/', max_length=50),
        ),
    ]
